### ISSUE TITLE
DocC regression - generated content is brutally slow.

### ISSUE THREAD

**Issue by migueldeicaza** [swiftlang/swift-docc-render#905]
### Description

I have published a site with DocC, and it can now take minutes to load on browsers.   The data transfer itself is instantaneous, but something is slowing down the rendering.   Even switching from one item to another can take 10-12 seconds.

The site in question is here:

https://migueldeicaza.github.io/SwiftGodotDocs/documentation/swiftgodot/

I know what you are thinking "The site is broken", well just give it some 10 minutes, and it will eventually render.

It is so slow that even attempting to open the Javascript console from Safari once you loaded the page does nothing.  You need to load the Javascript console first, then load the page to even see what it is doing.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Steps To Reproduce

The source code for the generated web site is here:

https://github.com/migueldeicaza/SwiftGodotDocs

Which is generated from this source:

https://github.com/migueldeicaza/SwiftGodot/

Which uses the following command:

```
GENERATE_DOCS=1 swift package \
		--allow-writing-to-directory $(ODOCS) \
		generate-documentation \
		--target SwiftGodot \
		--disable-indexing \
		--transform-for-static-hosting \
		--hosting-base-path /SwiftGodotDocs \
		--source-service github \
		--source-service-base-url https://github.com/migueldeicaza/SwiftGodot/blob/main \
		--checkout-path . \
		--emit-digest \
		--output-path $(ODOCS) \
		--verbose \
		>& build-docs.log
```

### Swift Compiler Version Information

```shell
swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0
```

**Comment by d-ronnqvist** [comment]
@mportiz08 does this look like it could be the same issues as https://github.com/swiftlang/swift-docc-render/issues/894 or that it could otherwise be fixed by the improvements in https://github.com/swiftlang/swift-docc-render/pull/900?

**Comment by mportiz08** [comment]
Yes, this sounds like #894 to me, which was recently fixed.

@migueldeicaza you can verify this in one of two ways:

* download the latest Swift toolchain and try to reproduce
* clone the latest [swift-docc-render-artifact][swift-docc-render-artifact] and add an additional environment variable to your existing command to build the docs as follows: `DOCC_HTML_DIR=/path/to/swift-docc-render-artifact/dist`

[swift-docc-render-artifact]: https://github.com/swiftlang/swift-docc-render-artifact/tree/main

**Comment by mportiz08** [comment]
We can re-open this to investigate further if you're still hitting this issue with the latest swift-docc-render

**Comment by migueldeicaza** [comment]
I used the swift-docc-render-artifact as suggested by @mportiz08 above and that seems to have fixed my issue.

Thank you!
